# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740fd1b2b04ad12032359227a6786317888c7509e870df27df75a5144f5967cad4f8c8d20a7dc80a09ace53aa74f8bd6146ea1447ce8991f44616a8fe555d1c7

test:
  secret_key_base: 777a2842e083456667bbfe94d92bd109a13f6477a8b019b7f263ff7412a376cd720fbf438ac266b1f3b77f2999968157eef3c47d0b0b1b0fad2b25ee7e127c19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
